db = db.getSiblingDB("shootizy");

db.ratings.insert([
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 6,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 1,
    comment: "It's ok !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 1.4,
    comment:
      "Shootizy is fucking great !Shootizy is fucking great !Shootizy is fucking great !Shootizy is fucking great !Shootizy is fucking great !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 1.6,
    comment: "It's ok !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 2,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 2.7,
    comment: "It's ok !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 3,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3.1,
    comment: "It's ok !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 3.2,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 5,
    comment: "It's ok !",
    isConfirmed: true,
  },

  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment:
      "Shootizy is fucking great ! Shootizy is fucking great ! Shootizy is fucking great ! Shootizy is fucking great !Shootizy is fucking great !Shootizy is fucking great ! Shootizy is fucking great ! Shootizy is fucking great !",
    isConfirmed: true,
  },
]);
