db = db.getSiblingDB("shootizy");

db.ratings.insert([
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 6,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 1,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 1,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 2,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 1.4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 3,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 1.6,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 4,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 2,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 5,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 2.7,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 6,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 3,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 7,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3.1,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 8,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 3.2,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 9,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 5,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 10,
  },

  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 11,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 12,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 13,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 14,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 15,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 16,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 17,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 18,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 19,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 20,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 21,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 22,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 23,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 24,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 25,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 26,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 27,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 28,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 29,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 30,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 31,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 32,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Arnaud Gueras",
    score: 4,
    comment: "Shootizy is fucking great !",
    isConfirmed: true,
    ratingId: 33,
  },
  {
    date: new Date(),
    shootingDate: new Date(),
    name: "Viet Vo",
    score: 3,
    comment: "It's ok !",
    isConfirmed: true,
    ratingId: 34,
  },
]);
